server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://192.168.50.9:3307/oa?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: oa
    password: "!QAZ2wsx"
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    hikari:
      max-lifetime: 6000000
      idle-timeout: 6000000
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: mysql-data-pool
      connection-timeout: 30000
      connection-test-query: select 1
  jpa:
    show-sql: true
